### ISSUE TITLE
Main Power more cannot be used as device in a Domoticz Scene

### ISSUE THREAD

**Issue by swevm** [jorgh6/domoticz-onkyo-plugin#11]
Am building scene that start my homecinema as I want when a button is pushed.

So far my simple things work as expected, like turning on/off a light, turning on Onkyo receiver, adjusting main volume to a defined level.

However setting Main Source to a predefined Input cannot be used in a Domoticz scenes due to can´t change Input only send "Command" or set "Level in %".

Expected behaviour is to see a dropdown where one can choose which Input to be set when scene is triggered.

**Comment by swevm** [comment]
Update:

This seem to be a general problem with Domoticz as same behaviour can be observed if a Dummy Selector Switch is added as a device to a scene.

A selector switch with 3 settings to choose between show up as a device where level (in %) can be set to 0, 10, 20 and 30%. While is should have read "Off", "Level1", "Level2" and "Level3"

**Comment by jorgh6** [comment]
As far as I know, this is indeed Domoticz behavior. The problem is even bigger when selecting levels above 100% as you can not select these levels when defining a scene from the web interface. It does seem to work from scripts.

**Comment by jorgh6** [comment]
Selecting the level associated with a specific input should work, however with the restriction that levels above 100 cannot be selected. This is more a Domoticz issue than a plugin issue.
